#include <iostream>
#include <vector>

using std::cout;
using std::cin;
using std::endl;
using std::vector;
using std::string;

int main(void) {
  vector<string> solutions {
    "4 - 4 * 4 * 4 = -60",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 - 4 - 4 * 4 = -16",
    "4 / 4 - 4 * 4 = -15",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 + 4 - 4 * 4 = -8",
    "4 / 4 - 4 - 4 = -7",
    "no solution",
    "no solution",
    "4 / 4 / 4 - 4 = -4",
    "no solution",
    "no solution",
    "4 - 4 - 4 / 4 = -1",
    "4 + 4 - 4 - 4 = 0",
    "4 + 4 / 4 - 4 = 1",
    "4 / 4 + 4 / 4 = 2",
    "no solution",
    "4 + 4 / 4 / 4 = 4",
    "no solution",
    "no solution",
    "4 + 4 - 4 / 4 = 7",
    "4 + 4 + 4 - 4 = 8",
    "4 + 4 + 4 / 4 = 9",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 * 4 - 4 / 4 = 15",
    "4 + 4 + 4 + 4 = 16",
    "4 * 4 + 4 / 4 = 17",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 + 4 + 4 * 4 = 24",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 * 4 + 4 * 4 = 32",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 * 4 * 4 - 4 = 60",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 + 4 * 4 * 4 = 68",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "no solution",
    "4 * 4 * 4 * 4 = 256"
  };
  cin.sync_with_stdio(false);
  cout.sync_with_stdio(false);

  int n_tests;
  cin >> n_tests;

  for (int i = 0; i < n_tests; i++) {
    int test;
    cin >> test;

    if (test >= -60 && test <= 256) {
      cout << solutions[test + 60] << endl;
    } else {
      cout << "no solution" << endl;
    }
  }
  return 0;
}
