name: adventlib
version: 1.0
id: adventlib-1.0
key: adventlib-1.0
category: Data Structures
exposed: True
exposed-modules:
    System.IO.Advent
    System.IO.Test
import-dirs: /home/samuel/src/monorepos/sams-monorepo/src/haskell/advent-lib/src/src
library-dirs: /home/samuel/src/monorepos/sams-monorepo/src/haskell/advent-lib/src/src
dynamic-library-dirs: /home/samuel/src/monorepos/sams-monorepo/src/haskell/advent-lib/src/src
hs-libraries: HSadventlib-1.0
depends:
    base-4.12.0.0
haddock-interfaces:
