PACKAGE-NAME := adventlib
PACKAGE-VERSION := 1.0
PACKAGE-DEPS := base lens parselib unliftio
EXPOSED-MODULES := Data.Advent Data.Bidim System.IO.Advent Text.Parsec.Advent Text.Parsec.Bidim
include $(HASKELL_LIB_MK)
