#!/usr/bin/env bash
#
# Like which, but following links

## Standard prelude
##====================================================================
set -e
set -u

readonly ARGS=("$@")
readonly NARGS="$#"
readonly PROGNAME="$(basename "$0")"

## Functions
##====================================================================
usage() {
    echo
    echo "Usage $PROGNAME <command>"
    echo
}

fail() {
    local message="$1"

    echo
    echo "$message"
    echo
    exit 1
}

main() {
    if (($NARGS != 1)); then
        usage
        exit 1
    fi

    readlink -f "$(which ${ARGS[0]})"
}

main
