#!/bin/sh
#
# Generate a random password with 18 bytes of entropy
#
# Since those are meant to be long living passwords, we use /dev/random instead
# of dev/urandom, so this script can block if the OS doesn't have enough entropy
# in the pool
#
# Assuming that the random value cannot be predicted, a pure brute force attack
# capable of generating 1.000.000 passwords per second would take
# 707151991328342945888372598701.4320619603 years to explore the password space,
# so we still have some room for imperfections

dd bs=1 count=18 if=/dev/random 2> /dev/null | base64
