#!/bin/bash

set -euo pipefail

readonly MSG_FILE="$1"
readonly BRANCH="$(git symbolic-ref HEAD)"
readonly TICKET_PREFIX="$(echo $BRANCH | sed -ne 's|.*/\(Q[0-9]*\)-.*$|\1|p')"
readonly CURRENT_PREFIX="$(sed -ne '1s|^\(Q[0-9]*: \).*|\1|p' "$MSG_FILE")"

if [[ -n "$TICKET_PREFIX" ]]; then
    sed -ie "1s/^$CURRENT_PREFIX/$TICKET_PREFIX: /" "$MSG_FILE"
fi
