PACKAGE-NAME := monad-emit
PACKAGE-VERSION := 1.0
PACKAGE-DEPS := base perlude generic-lens lens unliftio writer-cps-mtl
EXPOSED-MODULES := Control.Monad.MonadEmit Data.Metrics
include $(HASKELL_LIB_MK)
include $(TEST_HASKELL_MK)
