PACKAGE-NAME := searchlib
PACKAGE-VERSION := 1.0
PACKAGE-DEPS := base fingertree generic-lens lens perlude unordered-containers writer-cps-mtl
EXPOSED-MODULES := Control.Monad.MonadSearch Control.Monad.MonadSearch.Astar
include $(HASKELL_LIB_MK)

